### ISSUE TITLE
Images not displaying

### ISSUE THREAD

**Issue by weja** [infinity-next/infinity-next#224]
For some reason images stopped working for me few weeks ago.
They just do not display and show "broken image link" in browser.
It worked before, but there is also chance that I broke something..

You can see & try problem here:
https://8pallo.fi/test/thread/1

And btw, I had problem with posting before on nginx, that was fixed with this line:
/index.php$is_args$args (arguments had to be added like this, apache did it by default).

I know you're busy with migration, just wanted to add this here while I got nothing better to do :P

**Comment by jaw-sh** [comment]
That's not a valid URL.

**Comment by weja** [comment]
What is not valid URL ?
https://8pallo.fi doesn't work for you or is my configuration bad?

**Comment by QuakersOat** [comment]
I had this issue for a period of time, and it was solved by tweaking with my nginx block. My guess is that you've set your /path/to/next/storage/app/attachments wrong, and that is why images aren't displaying. Try tweaking with your configuration until you get it.

**Comment by b3y0ndd34th** [comment]
I am also experiencing this issue.

I believe I have the .env correct
APP_URL_MEDIA= (domain.tld)/infinityfolder/storage/app/attachments/

When I inspect the element the img src is set to
"http://(domain.tld)/infinityfolder/storage/app/attachments/file/thumb/2/1452368290-0.jpg?board=test"

Is this the correct behavior?  or have I not configured the .env correctly?

**Comment by jaw-sh** [comment]
Leave it blank if the domain is the same as your standard domain.

**Comment by b3y0ndd34th** [comment]
Leaving MEDIA in the .env blank does change the src.

Now I am looking at src="http://(domain.tld)/infinityfolder/public/index.php/b/file/thumb/4/1452390914-0.jpg"

but I still don't see any images.

**Comment by jaw-sh** [comment]
Your environment is misconfigured.

APP_URL=//larachan.foo
APP_URL_MEDIA=

**Comment by b3y0ndd34th** [comment]
No that's the way my .env file is set up.  After removing the info from the APP_URL_MEDIA I am able to see the images, but ONLY if I type in the index.php at the end of the URL.

If the index.php is missing from the URL, none of the board links or images work.

I will set up a fresh test later this afternoon to gather a better understanding on the issue.

**Comment by b3y0ndd34th** [comment]
The index.php issue was something completely different, thanks for the information on the .env settings.

**Comment by jaw-sh** [comment]
@b3y0ndd34th Are you still having this issue with my latest commit?

**Comment by TonySpahgetti** [comment]
Using the latest commit, having this issue as well, though, I feel it might be related to the .env config, since the uploads are in both storage/app/attachments and in the file_attachments table.

APP_URL=http://xx.xx.xx.xx
APP_URL_MEDIA=

==
Also verified that Apache was working.

**Comment by milezteg** [comment]
Guys it works 100% and always has with these settings:

`APP_URL=//larachan.foo`
`APP_URL_MEDIA=`

Just confirmed with my copy.

**Comment by TonySpahgetti** [comment]
No dice @milezteg 

It's most likely a backend configuration though, I'll keep digging in on my end.

**Comment by b3y0ndd34th** [comment]
I will give the latest commit a go when I get home this evening, thanks for your work on this.

**Comment by b3y0ndd34th** [comment]
Sorry but I still seem to be getting this issue.

I clone github to  /srv/www/website/

I set apache to server /srv/www/website/public as the root directory.

I run the composer update after adjusting only the APP_URL=//mychanname.tld and setting the information for my sql database in the .env file.  

Then when I browse to the site, none of the styling works, and images don't show.



If I set up a index.php on /srv/www/website to forward to /public/index.php while setting apache root directory to /srv/www/website, then the styling works as expected but the images still do not show.  I have to add "index.php" to the end of my URL in order for images to show.

I hope this helps to explain the issue.  I am running an Ubuntu 15.04 server with Apache 2.  I have used the recommended settings for apache  000-default.conf file. (except for when testing to see why the files, styling, or images are not showing)

Please let me know if there is something else I can do to narrow down the issue for you.

These are the issues that chrome reports (with the CORRECT set up you have recommended without any type of manipulating to get it to work)

Uncaught ReferenceError: jQuery is not defined (url.tld)/:354
Uncaught ReferenceError: PhpDebugBar is not defined  (url.tld)/:356
http://(url.tld)/test/file/thumb/7253d9680a676e5a95e24d3b530d8a57/1452474291-0.jpg Failed to load resource: the server responded with a status of 404 (Not Found)
http://(url.tld)/static/vendor/20-jquery-ui/jquery-ui.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://(url.tld)/static/vendor/20-jquery-ui/jquery-ui.structure.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://(url.tld)/static/vendor/20-jquery-ui/jquery-ui.theme.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://(url.tld)/static/vendor/50-boilerplate/css/main.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://(url.tld)/static/vendor/50-boilerplate/css/normalize.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://(url.tld)/static/vendor/60-unsemantic/unsemantic.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://(url.tld)/static/vendor/80-highlight/default.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://(url.tld)/static/vendor/font-awesome/css/font-awesome.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://(url.tld)/static/css/app/flags.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://(url.tld)/static/css/app/main.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://(url.tld)/_debugbar/assets/stylesheets?1450765358 Failed to load resource: the server responded with a status of 404 (Not Found)
http://(url.tld)/static/css/app/responsive.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://(url.tld)/static/css/skins/next-tomorrow.css Failed to load resource: the server responded with a status of 404 (Not Found)


These errors are reported even with global read permissions set, and it also occurs for global  read/write (I only do this for testing).

If I try to navigate to the 404'd files, I see them in my browser, so I can confirm the files are there and accessible.  But I am unsure why it is reported as a 404 when the file exists and is found.

**Comment by b3y0ndd34th** [comment]
Sorry but I still seem to be getting this issue.

I clone github to /srv/www/website/

I set apache to server /srv/www/website/public as the root directory.

I run the composer update after adjusting only the APP_URL=//mychanname.tld and setting the information for my sql database in the .env file.

Then when I browse to the site, the styling works, but images don't show.

I have to add "index.php" to the end of my URL in order for images to show.

I hope this helps to explain the issue. I am running an Ubuntu 15.04 server with Apache 2. I have used the recommended settings for apache 000-default.conf file. (except for when testing to see why the files, styling, or images are not showing)

Please let me know if there is something else I can do to narrow down the issue for you.

If I click on the board links, I get a 404 error with a url of http://(url.tld)/test

If I add /index.php at the end of my url, then I click the boards, I can browse the boards, but no images display.

**Comment by TonySpahgetti** [comment]
@b3y0ndd34th 

Strange, Was getting 500 errors too when I would refresh the "blank" image.
I'll nuke my server and try another fresh installation, was using CentOS 7.0 with PHP 5.6 and Apache 2

==
ErrorException in ImageController.php line 302:
filesize(): stat failed for /var/www/html/infinity-next/storage/app/attachments/full/5/c/6/6/5c66e7354410f2bcfb77ab8a5d3d97b7
in ImageController.php line 302
at HandleExceptions->handleError('2', 'filesize(): stat failed for /var/www/html/infinity-next/storage/app/attachments/full/5/c/6/6/5c66e7354410f2bcfb77ab8a5d3d97b7', '/var/www/html/infinity-next/app/Http/Controllers/Content/ImageController.php', '302', array('hash' => '5c66e7354410f2bcfb77ab8a5d3d97b7', 'filename' => '1452697203-0.jpg', 'thumbnail' => false, 'FileStorage' => object(FileStorage), 'storagePath' => 'attachments/full/5/c/6/6/5c66e7354410f2bcfb77ab8a5d3d97b7', 'storagePathFull' => '/var/www/html/infinity-next/storage/app/attachments/full/5/c/6/6/5c66e7354410f2bcfb77ab8a5d3d97b7', 'cacheTime' => '31536000', 'storageExists' => false))
----
Turns out the "Full" folder didn't exist, created it, and applied the appropriate permissions, only to get the same error.

**Comment by b3y0ndd34th** [comment]
I only get the 500 errors on the images themselves, not the pages.

**Comment by milezteg** [comment]
Latest changes break the Laravel debugger.  Try turning it off in your .env:

`APP_DEBUG=false`

**Comment by b3y0ndd34th** [comment]
Thanks for the info milezteg!

Unfortunately, the issues are still present with the debugger disabled :(

**Comment by milezteg** [comment]
Deb 8 + Php-fpm 5.6 + mysql

Make sure to do `php artisan clear:cache` 

Surprised that didn't fix it I had a similar issue.  Also be sure to `chmod -R 755 storage/app/attachments` for some reason it was set to `-r` for those.

**Comment by jaw-sh** [comment]
You should not have to 755 the attachments directory. Make sure you've given ownership permissions to your application that match your PHP daemon. 500 errors on images mean the image that should exist does not.

**Comment by TonySpahgetti** [comment]
I have storage/app/attachments owned by apache:apache. Still getting blank images, though the 500 errors upon refreshing, along with a spew of text has stopped.

Fresh installation, Centos 7.0 + Php-fpm 5.6 + MariaDB

will keep tinkering.

**Comment by Netifriik** [comment]
Having the same issue. Blank images on Ubuntu 14.04 and Apache. All the files are owned by www-data group and chmod 755 on the storage folder.

At first I somehow managed to see full images but thumbnails did not show. Now I can't see any images at all.

**Comment by milezteg** [comment]
Hmm I had this same issue but fixed it by making sure permissions were correct as well as disabling the laravel debugger.  Honestly though guys Josh is working on a caching layer so I wouldn't expect a lot of things to work 100% for at least a couple weeks.

**Comment by Netifriik** [comment]
Got the images to work using nginx. I have no idea..

**Comment by jaw-sh** [comment]
You did not have the X-SendFile module for Apache. It is included in all 
Nginx repository packages by default.

**Comment by Netifriik** [comment]
I did add X-SendFile to Apache config. Also downloaded the module.
But it's very possible I misconfigured something. Now I have an issue with captchas, images work but captcha's don't show up.

**Comment by Graham--M** [comment]
I thought it was supposed to work without xsendfile too? I couldn't get the php only output to work. So I installed the module, enabled it in the apache config, and enabled it in the vhost config with the correct directory set.

Then the server stopped sending the xsendfile header but I was still getting 0kb and a filetype header so something else was wrong.

I traced the pipeline execution to `Barryvdh\HttpCache\Middleware\CacheRequests` as the request wasn't touching the `ImageController.php` or the router.

Turns out @milezteg was slightly off. The command to clear the cache is:
`php artisan httpcache:clear`
and that got it to serve attachments properly. Whew.

**Comment by Netifriik** [comment]
Any idea why my captcha is not working? Also a bit offtopic but are .webm filetypes supported? I seem to be getting integrity check errors.

**Comment by Graham--M** [comment]
@Netifriik, I had a look. Captchas aren't working for me either. Similar problem as before; the cacherequests middleware seems to swallow the captcha image. I'm not sure if I should be seeing those cache headers for a captcha image?

```
Age: 0
Cache-Control: max-age=86400, pre-check=86400, public
Connection: Keep-Alive
Content-Disposition: inline
Content-Length: 0
Content-Type: image/png
Date: Fri, 15 Jan 2016 19:54:43 GMT
Expires: Sat, 16 Jan 2016 19:54:44 +0000
Keep-Alive: timeout=5, max=100
Last-Modified: Fri, 15 Jan 2016 19:36:56 +0000
Server: Apache/2.4.7 (Ubuntu)
Set-Cookie: laravel_session=[snipped for readability]
X-Powered-By: PHP/5.5.9-1ubuntu4.14
X-Symfony-Cache: GET /cp/captcha/default/611b11609e95afde9af0213a8d8640b4f6d0a895.png: miss, store
filename: 611b11609e95afde9af0213a8d8640b4f6d0a895.png
x-content-digest: [snipped for readability]
```

**Comment by Netifriik** [comment]
It has something to do with the `Response::stream` method. If I replace the Streaming Response in `getAsResponse($profile = "default")` function with a simple `Response::make` function it works.

**Comment by Graham--M** [comment]
@Netifriik Yeah. The `symfony/StreamedResponse` returns `false` for `getContent()` because it's meant to be streamed but that is what the `symfony/HttpCache` uses to cache the request and it overwrites the `Content-Length` size with `strlen($response->getContent())` which cast to a number gives a length of zero.

If you comment [this line](https://github.com/symfony/symfony/blob/da655a93687fb93027434592dc739ff9a20941f2/src/Symfony/Component/HttpKernel/HttpCache/Store.php#L185) out then it serves the image correctly (but the server cache is still wrong).

**Comment by TonySpahgetti** [comment]
Still getting the issue on Apache, permissions are correct, Xsendfile is configured and loaded, debugger disabled, cleared the httpcache.

No dice on my end, I'll try switching over to NGINX

**Comment by jaw-sh** [comment]
I've discovered recently that xSendFiles won't active using PHP5-FPM 
with Apache because there's no way for me to determine if it's actually 
enabled. You can either use Nginx or mod_php.

**Comment by b3y0ndd34th** [comment]
Thanks for the info Josh, I was going to make a post this afternoon after work.

I did some HEAVY testing this weekend using Ubuntu and Debain.  I was not able to use Apache and xsendfile.

I will try to set up mod_php.  (not familiar with nginx is all).  If I am unable to get that to work, I will try to learn nginx.

**Comment by b3y0ndd34th** [comment]
I am setting up nginx on a test server at the moment.

Like I said, I have no experience with nginx, so I am bound to have errors.

I have run out of time for the evening.  I got everything installed and I will do some troubleshooting tomorrow.  Right now I get a blank page when it tries to load the index.php.

I will provide more info when I can.

**Comment by Graham--M** [comment]
@b3y0ndd34th Are you done with Apache and mod_php then? Remember that `x-sendfile` has to be enabled for the virtual host itself (here's a quick example):

```
/etc/apache2/sites-available/next.conf

<VirtualHost *:80>
    DocumentRoot "/var/www/next/public"
    
    <Directory "/var/www/next/public">
        AllowOverride all
    </Directory>
    
    <IfModule mod_xsendfile.c>
        XSendFile on
        XSendFilePath "/var/www/next"
    </IfModule>
</VirtualHost>
```

**Comment by b3y0ndd34th** [comment]
@Graham--M Thanks for the reply.

I would REALLY like to use Apache, as I have a web server with a number of projects already set up and working properly through Apache.  This would be a nice addition.

If I have to use nginx, I will have to build a new server and learn to port everything to that server ( I want to have an Apache fallback just in case, it is what I am comfortable with).

Here is the CURRENT output of my Apache conf for the domain.   I have tried various set ups in the Apache config to try to figure out where the issue was and this was the last one I tried.

<VirtualHost *:80>
    ServerName domain.tk
    ServerAlias *.domain.tk

    DocumentRoot /srv/www/website/public
<Directory "/srv/www/website/public">
        AllowOverride all
</Directory>

    DirectoryIndex index.php

<IfModule mod_xsendfile.c>
        XSendFile on
        XSendFilePath "/srv/www/website/"
    </IfModule>
</VirtualHost>

I've had XSendFile enabled since beginning this project.

But none of the images that are submitted to the board show :(
Only the logos from the srv/www/domain/public/static folder will show.




The reason I was attempting to set up nginx, is because some have reported success, and I wanted to eliminate the Apache variable as my issue.  

I can provide my nginx information and error logs later (I powered the server off last night when I was done for the night)

**Comment by Graham--M** [comment]
@b3y0ndd34th That config looks similar to what I've got and it looks like you've got xsendfile installed properly since I assume what you pasted was the loaded modules dump output and it's in there.

First time I started the server and I didn't have xsendfile configured properly, it wound up caching the broken responses and it didn't work, even after I configured it properly. After I did ```php artisan httpcache:clear``` to clear the cache and that fixed it.

If clearing the cache isn't working then you could have a look to see what headers the server is sending you. In chrome if you open an attachment in a tab, right click and choose inspect, switch to the network tab in the developer tools, and hit CTRL + F5 and click on the request, you should see the response headers.

I'm guessing you'll have a status of 200 and a `Content-Length` of 0 but if you see the `X-Sendfile` header then the module isn't handling the response.

**Comment by b3y0ndd34th** [comment]
I have tried the ```php artisan httpcache:clear```  a few times now but I haven't had luck with it :(

Source
```The response header for the image is:
HTTP/1.0 500 Internal Server Error
Cache-Control:no-cache, private
Connection:close
Content-Length:4519
Content-Type:text/html; charset=UTF-8
Date:Wed, 20 Jan 2016 01:21:35 GMT
Server:Apache/2.4.10 (Ubuntu)```

Parsed
```Date: Wed, 20 Jan 2016 01:21:35 GMT
Server: Apache/2.4.10 (Ubuntu)
Cache-Control: no-cache, private
Content-Length: 4519
Connection: close
Content-Type: text/html; charset=UTF-8```

**Comment by Graham--M** [comment]
@b3y0ndd34th From the headers you had in your original post, it definitely wasn't a cache problem and I can't see what would have fixed it in the commits, but I'm glad it's working for you now.

@jaw-sh I see you fixed the captcha to use `Response::make`. Are you aware that you are still using `Response::stream` [here](https://github.com/infinity-next/infinity-next/blob/d30bbf1807f7e82a3b47c297239424bd0cf70f92/app/Http/Controllers/Content/ImageController.php#L427) for images?

**Comment by TonySpahgetti** [comment]
I've configured it in NGINX and am having the same issues with the images, though, I feel as if it's my NGINX configuration (as it's a  *107 rewrite or internal redirection cycle while internally redirecting to, error)

which is a start, I'll post an update once I'm good on my end, and note all the steps
Thank ye @Graham--M  and @jaw-sh @milezteg for all the assistance.

**Comment by weja** [comment]
I don't have a slightest clue what could be the problem.. 
I have both nginx and apache running on same web root, but on different ports.
Both have same problem, images do not display very similar way.. I've done my all, configured nginx and apache all possible ways, no idea what could be causing this.. It worked before on both web servers by just setting the webroot folder..

http://8pallo.fi <- nginx
http://8pallo.fi:81 <- apache, xsendfile manually enabled

**Comment by jaw-sh** [comment]
I get a 500 error trying to access this directly:
http://8pallo.fi/test/file/thumb/44f70285b414f85ae0f21c7eae75ba5a/1453325695-0.jpg

Do you see anything in your Nginx error log?

**Comment by weja** [comment]
I found installation instructions for Next, now it works on nginx..
This was required part (was not required before, sure it worked before, heh):

    location /attachments {
        internal;
        # Yes, this must be an absolute path.
        # You're in for a bad time if it isn't.
        alias /my/path/to/next/storage/app/attachments;
    }

Now it all works on nginx. But not on apache though!
